-- =============================================
-- Subcategory table
-- =============================================

CREATE TABLE public.subcategory
(
    id          int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name"      varchar(40)                                       NOT NULL,
    essential   bool      DEFAULT false                           NOT NULL,
    active      bool      DEFAULT true                            NOT NULL,
    category_id int4                                              NOT NULL,
    created_at  timestamptz                                       NOT NULL,
    updated_at  timestamptz                                       NOT NULL,
    CONSTRAINT subcategory_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category (id) ON DELETE CASCADE
);

CREATE INDEX subcategory_category_id_idx ON public.subcategory USING btree (category_id);

-- Reuse the existing audit trigger function for created_at/updated_at
CREATE TRIGGER tr_before_events_subcategory_audit_fields
    BEFORE INSERT OR UPDATE
    ON public.subcategory
    FOR EACH ROW
EXECUTE FUNCTION public.fu_before_events_audit_fields();

-- =============================================
-- Add subcategory_id to release
-- =============================================

ALTER TABLE public.release
    ADD COLUMN subcategory_id int4 NULL;

ALTER TABLE public.release
    ADD CONSTRAINT release_subcategory_id_fkey FOREIGN KEY (subcategory_id) REFERENCES public.subcategory (id);

CREATE INDEX release_subcategory_id_idx ON public.release USING btree (subcategory_id);

-- =============================================
-- Trigger: validate subcategory belongs to the
-- informed category on release insert/update
-- =============================================

CREATE OR REPLACE FUNCTION public.fu_before_validate_release_subcategory()
    RETURNS trigger
    LANGUAGE plpgsql
AS
$function$
BEGIN

    IF NEW.subcategory_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM public.subcategory
            WHERE id = NEW.subcategory_id
              AND category_id = NEW.category_id
        ) THEN
            RAISE EXCEPTION 'Subcategory % does not belong to category %', NEW.subcategory_id, NEW.category_id;
        END IF;
    END IF;

    RETURN NEW;

END;
$function$;

CREATE TRIGGER tr_before_validate_release_subcategory
    BEFORE INSERT OR UPDATE
    ON public.release
    FOR EACH ROW
EXECUTE FUNCTION public.fu_before_validate_release_subcategory();

